workflows:
  ios-pwa-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "ukcemap.co.uk.xcodeproj"
        XCODE_SCHEME: "ukcemap.co.uk"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build/UKCEMAP.xcarchive archive
    artifacts:
      - build/UKCEMAP.xcarchive
