workflows:
  ios-pwa-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ukcemap.co.uk.xcworkspace"
        XCODE_SCHEME: "ukcemap.co.uk"
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build/UKCEMAP.xcarchive archive
    artifacts:
      - build/UKCEMAP.xcarchive
